---
# morpheus is now running on nixOS
# the only configuration that should be present here is the
# docker-compose role generator container definitions

ntp_timezone: "America/New_York"

# ktz.htop
htoprc_filename: htoprc-morpheus

# ironicbadger.docker_compose_generator
appdata_path: /mnt/appdata
download_path: /mnt/downloads
storage_path: /mnt/jbod
bigrust18_path: /mnt/bigrust18
wd_domain_me: "wd.{{ domain_me }}"
m_wd_domain_me: "m.{{ wd_domain_me }}"

docker_compose_generator_uid: "1000"
docker_compose_generator_gid: "1000"
global_env_vars:
  - "PUID={{ docker_compose_generator_uid }}"
  - "PGID={{ docker_compose_generator_gid }}"
  - "TZ={{ ntp_timezone }}"

containers:
  ### Administrative
  ###
  - service_name: tr
    active: true
    image: traefik
    container_name: tr
    labels:
      - traefik.enable=false
    ports:
      - 80:80
      - 443:443
    command:
      - --log.level=info
      - --accesslog=false
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - "--certificatesresolvers.cloudflare.acme.email={{ cloudflare_account_email }}"
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --serversTransport.insecureSkipVerify=true
    volumes:
      - "{{ appdata_path }}/apps/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "CLOUDFLARE_EMAIL={{ cloudflare_account_email }}"
      - "CLOUDFLARE_API_KEY={{ cloudflare_api_key }}"
    restart: unless-stopped
  ### Media Servers
  ###
  - service_name: jellyfin
    active: true
    image: jellyfin/jellyfin
    hostname: us-rdu
    devices:
      - /dev/dri:/dev/dri
    labels:
      - traefik.enable=true
      - "traefik.http.routers.jellyfin.rule=Host(`jf.{{ wd_domain_me }}`)"
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    ports:
      - 2285:8096
    volumes:
      - "{{ appdata_path }}/mediaservers/jellyfin:/config"
      - "{{ storage_path }}:/data:ro"
      - "{{ bigrust18_path }}/media:/bigrust18/media:ro"
      # ram transcode
      - /dev/shm:/transcode
    environment:
      - "JELLYFIN_PublishedServerUrl=jf.{{ wd_domain_me }}"
    include_global_env_vars: true
    restart: unless-stopped
  ###
  - service_name: plex
    active: true
    image: plexinc/pms-docker
    network_mode: host
    labels:
      - traefik.enable=false
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - "{{ appdata_path }}/mediaservers/plex/config:/config"
      - "{{ storage_path }}:/data:ro"
      - "{{ bigrust18_path }}/media:/bigrust18/media:ro"
      # ram transcode
      - /dev/shm:/transcode"
    include_global_env_vars: true
    restart: unless-stopped
  ###
  - service_name: abs
    active: true
    image: advplyr/audiobookshelf
    labels:
      - traefik.enable=true
      - "traefik.http.routers.audiobookshelf.rule=Host(`abs.{{ wd_domain_me }}`)"
    ports: # shared via caddy and tailscale
      - 2284:80
    volumes:
      - "{{ bigrust18_path }}/media/audiobooks/library:/audiobooks:ro"
      - "{{ bigrust18_path }}/media/audiobooks/library2:/audiobooks2:ro"
      - "{{ bigrust18_path }}/media/audiobooks/podcasts:/podcasts"
      - "{{ appdata_path }}/mediaservers/audiobookshelf/metadata:/metadata"
      - "{{ appdata_path }}/mediaservers/audiobookshelf/config:/config"
    restart: unless-stopped

  ### Media Apps
  ###
  ###
  - service_name: prowlarr
    active: true
    image: lscr.io/linuxserver/prowlarr:develop
    labels:
      - traefik.enable=true
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.{{ m_wd_domain_me }}`)"
    volumes:
      - "{{ appdata_path }}/arrmatey/prowlarr:/config"
    include_global_env_vars: true
    restart: unless-stopped
  ###
  - service_name: sabnzbd
    active: true
    image: lscr.io/linuxserver/sabnzbd
    volumes:
      - "{{ appdata_path }}/arrmatey/sabnzbd:/config"
      - "{{ download_path }}:/downloads"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.{{ m_wd_domain_me }}`)"
    depends_on:
      - prowlarr
    include_global_env_vars: true
    restart: unless-stopped
  ###
  - service_name: sonarr
    active: true
    image: lscr.io/linuxserver/sonarr
    depends_on:
      - sabnzbd
      - prowlarr
    labels:
      - traefik.enable=true
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.{{ m_wd_domain_me }}`)"
    volumes:
      - "{{ appdata_path }}/arrmatey/sonarr:/config"
      - "{{ download_path }}/complete/tv:/downloads/complete/tv"
      - /mnt/jbod/tv:/tv
    include_global_env_vars: true
    restart: unless-stopped
  ###
  - service_name: radarr
    active: true
    image: lscr.io/linuxserver/radarr
    volumes:
      - "{{ appdata_path }}/arrmatey/radarr:/config"
      - "{{ download_path }}/complete/movies:/downloads/complete/movies"
      - /mnt/jbod/movies:/movies
    labels:
      - traefik.enable=true
      - "traefik.http.routers.radarr.rule=Host(`radarr.{{ m_wd_domain_me }}`)"
    include_global_env_vars: true
    restart: unless-stopped

  ### Monitoring and Tools
  ###
  - service_name: smokeping
    active: true
    image: lscr.io/linuxserver/smokeping
    hostname: morpheus
    volumes:
      - "{{ appdata_path }}/apps/smokeping/config:/config"
      - "{{ appdata_path }}/apps/smokeping/data:/data"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.smokeping.rule=Host(`smokeping.{{ m_wd_domain_me }}`)"
    include_global_env_vars: true
    restart: unless-stopped
  ###
  - service_name: librespeed
    active: true
    image: lscr.io/linuxserver/librespeed
    labels:
      - traefik.enable=false
    ports:
      - 8008:80
    environment:
      - MODE=standalone
    restart: unless-stopped